# Generated by Django 4.1.7 on 2023-04-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('Male', 'male'), ('Female', 'Female')], max_length=100)),
                ('Age', models.IntegerField()),
                ('Medical_Specialties', models.CharField(choices=[('Orthopedics', 'Orthopedics'), ('Internal Medicine', 'Internal Medicine'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatric'), ('Radiology', ' Radiology'), ('General Surgery', ' General Surgery'), ('Ophthalmology', 'Ophthalmolog')], max_length=500)),
                ('Date_and_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
